import { Injectable, signal } from '@angular/core';

export type AppLanguage = 'en' | 'es';

const ES: Record<string, string> = {
  dashboard: 'Panel principal', buildings: 'Edificios', monitoring: 'Monitoreo de pisos',
  spaces: 'Espacios', devices: 'Dispositivos', alerts: 'Alertas', incidents: 'Incidentes',
  analytics: 'Analíticas', settings: 'Configuración', search: 'Buscar espacios, dispositivos...',
  notifications: 'Notificaciones', recent: 'recientemente', viewAlerts: 'Ver todas las alertas',
  administrator: 'Administrador', signOut: 'Cerrar sesión', profile: 'Perfil', preferences: 'Preferencias',
  security: 'Seguridad y acceso', contactInfo: 'Información de contacto', languageNotifications: 'Idioma y notificaciones',
  sessionInfo: 'Información de sesión IAM', loadingProfile: 'Cargando tu perfil...', personalInfo: 'Información personal y de contacto de tu cuenta.',
  accountOverview: 'Resumen de la cuenta', firstName: 'Nombre', lastName: 'Apellido', fullName: 'Nombre completo',
  userId: 'ID de usuario', role: 'Rol', accountStatus: 'Estado de la cuenta', active: 'Activa',
  email: 'Correo electrónico', phone: 'Número de teléfono', enterPhone: 'Ingresa el número de teléfono',
  reset: 'Restablecer', saveContact: 'Guardar información de contacto', saving: 'Guardando...',
  preferencesDescription: 'Configura el idioma, zona horaria y las notificaciones SMS.',
  applicationLanguage: 'Idioma de la aplicación', english: 'Inglés', spanish: 'Español', timeZone: 'Zona horaria',
  smsAlerts: 'Alertas por SMS', smsHelp: 'Permitir que ResQ envíe alertas al teléfono registrado.',
  languageApplied: 'El idioma se aplica inmediatamente y se conserva para futuras sesiones.',
  savePreferences: 'Guardar preferencias', authenticationState: 'Estado de autenticación', authenticated: 'Autenticado',
  localProfile: 'Solo perfil local', identityId: 'ID de identidad', unavailable: 'No disponible',
  roleManagement: 'Administración de roles', roleHelp: 'Los roles son administrados por el servicio de identidad.',
  endSession: 'Finalizar esta sesión', endSessionHelp: 'Limpia la sesión y el perfil actual del frontend.',
};

const UI_ES: Record<string, string> = {
  'Dashboard': 'Panel principal', 'Buildings': 'Edificios', 'Floor Monitoring': 'Monitoreo de pisos',
  'Spaces': 'Espacios', 'Devices': 'Dispositivos', 'Alerts': 'Alertas', 'Incidents': 'Incidentes',
  'Analytics': 'Analíticas', 'Settings': 'Configuración', 'Overview': 'Resumen', 'History': 'Historial',
  'Profile': 'Perfil', 'Preferences': 'Preferencias', 'Security & Access': 'Seguridad y acceso',
  'Search spaces, devices...': 'Buscar espacios, dispositivos...', 'Notifications': 'Notificaciones',
  'View all alerts': 'Ver todas las alertas', 'Administrator': 'Administrador', 'Sign out': 'Cerrar sesión',
  'Welcome back': 'Bienvenido de nuevo', 'Sign in': 'Iniciar sesión', 'Signing in...': 'Iniciando sesión...',
  'Email address': 'Correo electrónico', 'Password': 'Contraseña', 'Demo credentials': 'Credenciales de demostración',
  'Connected building intelligence': 'Inteligencia para edificios conectados',
  'See risk sooner.': 'Detecta el riesgo antes.', 'Respond with confidence.': 'Responde con confianza.',
  'Connected devices': 'Dispositivos conectados', 'System uptime': 'Disponibilidad del sistema', 'Live monitoring': 'Monitoreo en vivo',
  'English': 'Inglés', 'Spanish': 'Español', 'Application language': 'Idioma de la aplicación',
  'Time zone': 'Zona horaria', 'SMS alerts': 'Alertas por SMS', 'Save preferences': 'Guardar preferencias',
  'Reset': 'Restablecer', 'Save contact information': 'Guardar información de contacto', 'Saving...': 'Guardando...',
  'Add Building': 'Agregar edificio', 'Edit Building': 'Editar edificio', 'Delete Building': 'Eliminar edificio',
  'View Building': 'Ver edificio', 'Monitor Floor': 'Monitorear piso', 'Building Overview': 'Resumen del edificio',
  'Building Information': 'Información del edificio', 'Building Name': 'Nombre del edificio', 'Address': 'Dirección',
  'Description': 'Descripción', 'Building': 'Edificio', 'Floors': 'Pisos', 'Floor': 'Piso',
  'Monitored Spaces': 'Espacios monitoreados', 'Active Alerts': 'Alertas activas', 'Active Devices': 'Dispositivos activos',
  'Critical Spaces': 'Espacios críticos', 'Building Floors': 'Pisos del edificio', 'Building Status Summary': 'Resumen del estado del edificio',
  'Floor Plan Editor': 'Editor del plano', 'Configure Floor Plan': 'Configurar plano', 'Edit Plan': 'Editar plano',
  'Clear Plan': 'Limpiar plano', 'Save Floor Plan': 'Guardar plano', 'Floor plan not configured': 'Plano no configurado',
  'Floor Plan: Configured': 'Plano: configurado', 'Floor Plan: Not Configured': 'Plano: no configurado',
  '2D View': 'Vista 2D', '3D View': 'Vista 3D', 'Normal': 'Normal', 'Warning': 'Advertencia',
  'Critical': 'Crítico', 'Offline': 'Sin conexión', 'Online': 'En línea', 'All': 'Todos',
  'All buildings': 'Todos los edificios', 'All floors': 'Todos los pisos', 'All types': 'Todos los tipos',
  'All statuses': 'Todos los estados', 'All Status': 'Todos los estados', 'All risk levels': 'Todos los niveles de riesgo',
  'All severities': 'Todas las severidades', 'All capabilities': 'Todas las capacidades', 'All zones': 'Todas las zonas',
  'Search': 'Buscar', 'Filters': 'Filtros', 'Back': 'Volver', 'Cancel': 'Cancelar', 'Continue': 'Continuar',
  'Apply Changes': 'Aplicar cambios', 'Confirm changes': 'Confirmar cambios', 'Delete': 'Eliminar', 'Edit': 'Editar',
  'Details': 'Detalles', 'Open': 'Abierto', 'Closed': 'Cerrado', 'Active': 'Activo', 'In Progress': 'En progreso',
  'Resolved': 'Resuelto', 'Status': 'Estado', 'Type': 'Tipo', 'Code': 'Código', 'Name': 'Nombre',
  'Display Name': 'Nombre visible', 'Technical Name': 'Nombre técnico', 'Assigned Space': 'Espacio asignado',
  'Assigned Location': 'Ubicación asignada', 'Position': 'Posición', 'Latest Reading': 'Última lectura',
  'Battery': 'Batería', 'Signal': 'Señal', 'Last Seen': 'Visto por última vez', 'Last Heartbeat': 'Último latido',
  'Device Status': 'Estado de dispositivos', 'Device Catalog': 'Catálogo de dispositivos',
  'Device Management': 'Gestión de dispositivos', 'Device Capabilities': 'Capacidades del dispositivo',
  'Add Device': 'Agregar dispositivo', 'Delete Device': 'Eliminar dispositivo', 'Remove from Plan': 'Quitar del plano',
  'Temperature': 'Temperatura', 'Smoke': 'Humo', 'Gas': 'Gas', 'Humidity': 'Humedad', 'Motion': 'Movimiento',
  'Current Reading': 'Lectura actual', 'Current Conditions': 'Condiciones actuales',
  'Environmental History': 'Historial ambiental', 'Environmental Overview': 'Resumen ambiental',
  'Monitoring Configuration': 'Configuración de monitoreo', 'Sensitivity': 'Sensibilidad',
  'Sensitivity level': 'Nivel de sensibilidad', 'Environmental thresholds': 'Umbrales ambientales',
  'Low': 'Baja', 'High': 'Alta', 'Custom': 'Personalizada', 'Warning threshold': 'Umbral de advertencia',
  'Critical threshold': 'Umbral crítico', 'Save configuration': 'Guardar configuración',
  'Alerts Over Time': 'Alertas en el tiempo', 'Alerts by Severity': 'Alertas por severidad',
  'Total Alerts': 'Total de alertas', 'Total Incidents': 'Total de incidentes',
  'Avg. Resolution Time': 'Tiempo promedio de resolución', 'Device Online Rate': 'Tasa de dispositivos en línea',
  'Most Affected Zones': 'Zonas más afectadas', 'Devices by Connectivity': 'Dispositivos por conectividad',
  'Monitoring Measurements': 'Mediciones de monitoreo', 'Incidents Over Time': 'Incidentes en el tiempo',
  'Resolution Performance': 'Rendimiento de resolución', 'Analysis period': 'Período de análisis',
  'Last 24 Hours': 'Últimas 24 horas', 'Last 7 Days': 'Últimos 7 días', 'Last 30 Days': 'Últimos 30 días',
  'All variables': 'Todas las variables', 'Critical Alerts': 'Alertas críticas', 'Alert Context': 'Contexto de alerta',
  'Detection Evidence': 'Evidencia de detección', 'Delivery': 'Entrega', 'Authorization': 'Autorización',
  'Approve': 'Aprobar', 'Reject': 'Rechazar', 'Alert Not Found': 'Alerta no encontrada',
  'Incident context': 'Contexto del incidente', 'Incident lifecycle': 'Ciclo de vida del incidente',
  'Assign to me': 'Asignarme', 'Confirm resolution': 'Confirmar resolución', 'Back to Incidents': 'Volver a incidentes',
  'Back to Devices': 'Volver a dispositivos', 'Back to Buildings': 'Volver a edificios',
  'Back to Dashboard': 'Volver al panel', 'Device Not Found': 'Dispositivo no encontrado',
  'Building not found': 'Edificio no encontrado', 'Floor not found': 'Piso no encontrado',
  'Space not found': 'Espacio no encontrado', 'Profile information': 'Información del perfil',
  'Account overview': 'Resumen de la cuenta', 'First name': 'Nombre', 'Last name': 'Apellido',
  'Full name': 'Nombre completo', 'User ID': 'ID de usuario', 'Role': 'Rol', 'Account status': 'Estado de cuenta',
  'Phone number': 'Número de teléfono', 'Authentication state': 'Estado de autenticación',
  'Authenticated': 'Autenticado', 'Local profile only': 'Solo perfil local', 'Identity ID': 'ID de identidad',
  'Role management': 'Administración de roles', 'End this session': 'Finalizar esta sesión',
  'Loading...': 'Cargando...', 'No data available': 'No hay datos disponibles', 'View All': 'Ver todo',
  'Activate': 'Activar', 'Deactivate': 'Desactivar', 'Administrative': 'Administrativo',
  'Administrative status': 'Estado administrativo', 'Alert': 'Alerta', 'Alert ID': 'ID de alerta',
  'All connectivity': 'Toda conectividad', 'All risks': 'Todos los riesgos', 'All time': 'Todo el período',
  'Area': 'Área', 'Areas': 'Áreas', 'Assigned to': 'Asignado a',
  'Assignment': 'Asignación', 'Average': 'Promedio', 'Basic information': 'Información básica',
  'Building Image': 'Imagen del edificio', 'Building Info': 'Información del edificio',
  'Buildings with Active Alerts': 'Edificios con alertas activas', 'Capabilities': 'Capacidades',
  'Capability': 'Capacidad', 'Choose image': 'Elegir imagen', 'Completed': 'Completado',
  'Connectivity': 'Conectividad', 'Connectivity Management': 'Gestión de conectividad', 'Create as New Space': 'Crear como espacio nuevo',
  'Created': 'Creado', 'Decision': 'Decisión', 'Delete Area': 'Eliminar área',
  'Delete Area and Space': 'Eliminar área y espacio', 'Delete Area Only': 'Eliminar solo el área',
  'Delete Area?': '¿Eliminar área?', 'Delete element': 'Eliminar elemento', 'Destination': 'Destino',
  'Detected': 'Detectado', 'Detected At': 'Detectado el', 'Device': 'Dispositivo',
  'Device Alerts': 'Alertas del dispositivo', 'Device Code': 'Código del dispositivo',
  'Distribution of buildings by current status': 'Distribución de edificios por estado actual',
  'Draw a new area, then configure or link it to a monitored space.': 'Dibuja un área nueva y luego configúrala o vincúlala a un espacio monitoreado.',
  'Each sensitivity level keeps its own warning and critical thresholds.': 'Cada nivel de sensibilidad conserva sus propios umbrales de advertencia y críticos.',
  'Earthquake': 'Terremoto', 'Edit details': 'Editar detalles', 'Environmental Readings (Last 24 Hours)': 'Lecturas ambientales (últimas 24 horas)',
  'Failure reason': 'Motivo del fallo', 'Fire': 'Incendio', 'Fleet connectivity': 'Conectividad de la flota',
  'Floor Configuration': 'Configuración del piso', 'Floor name': 'Nombre del piso',
  'Floor plan background': 'Fondo del plano', 'Floor Status': 'Estado del piso', 'Gas leak': 'Fuga de gas',
  'Gas Level': 'Nivel de gas', 'Generated At': 'Generada el', 'Geometry': 'Geometría', 'Grid': 'Cuadrícula',
  'Grid View': 'Vista de cuadrícula', 'Hardware Reference': 'Referencia de hardware', 'Height': 'Alto',
  'Info': 'Información', 'Incident created': 'Incidente creado', 'Incident not found': 'Incidente no encontrado',
  'Incident Relation': 'Relación con incidente', 'Label': 'Etiqueta', 'Latest classified risks': 'Últimos riesgos clasificados',
  'Latest events across all buildings': 'Últimos eventos de todos los edificios', 'Linked Space': 'Espacio vinculado',
  'Live building and floor overview': 'Resumen en vivo del edificio y el piso', 'Live data updated moments ago': 'Datos en vivo actualizados hace unos momentos',
  'Live space status': 'Estado del espacio en vivo', 'Location': 'Ubicación',
  'Manage and monitor your connected buildings': 'Administra y monitorea tus edificios conectados',
  'Manufacturer': 'Fabricante', 'Maximum': 'Máximo', 'Measured': 'Medido', 'Minimum': 'Mínimo',
  'Model': 'Modelo', 'Monitor': 'Monitorear', 'Monitored Floors': 'Pisos monitoreados',
  'Monitoring availability': 'Disponibilidad de monitoreo', 'Most Alerts': 'Más alertas',
  'Most Critical': 'Más críticos', 'Most Devices': 'Más dispositivos', 'Name *': 'Nombre *',
  'No areas yet': 'Aún no hay áreas', 'No devices on this floor.': 'No hay dispositivos en este piso.',
  'No image': 'Sin imagen', 'No notification deliveries were requested.': 'No se solicitaron entregas de notificaciones.',
  'No zone': 'Sin zona', 'Not set': 'No configurado', 'Notification Delivery': 'Entrega de notificación',
  'Number of Floors *': 'Número de pisos *', 'Offline / Timeout': 'Sin conexión / tiempo agotado',
  'Offline Devices': 'Dispositivos sin conexión', 'Open assigned space': 'Abrir espacio asignado',
  'Open full space details': 'Abrir detalles completos del espacio', 'Open space details': 'Abrir detalles del espacio',
  'Other': 'Otro', 'Page not found': 'Página no encontrada', 'Period': 'Período',
  'Position X': 'Posición X', 'Position Y': 'Posición Y', 'Properties': 'Propiedades',
  'Reading History': 'Historial de lecturas', 'Recent Building Activity': 'Actividad reciente del edificio',
  'Recent Incidents': 'Incidentes recientes', 'Recipient': 'Destinatario', 'Remove image': 'Quitar imagen',
  'Replace Assignment': 'Cambiar asignación', 'Requested': 'Solicitado', 'Reset filters': 'Restablecer filtros',
  'Resolution': 'Resolución', 'Resolution notes': 'Notas de resolución', 'Resolve incident': 'Resolver incidente',
  'Resolved incidents': 'Incidentes resueltos', 'Response activity': 'Actividad de respuesta', 'Result': 'Resultado',
  'Retire': 'Retirar', 'Review': 'Revisar', 'Review Building': 'Revisar edificio', 'Risk': 'Riesgo',
  'Risk Detection': 'Detección de riesgo', 'Risk Detection ID': 'ID de detección de riesgo',
  'Risk Distribution': 'Distribución de riesgos', 'Risk history': 'Historial de riesgos',
  'Risk level': 'Nivel de riesgo', 'Risk status': 'Estado de riesgo', 'Risk Type': 'Tipo de riesgo',
  'Room Number': 'Número de sala', 'Rotation': 'Rotación', 'Save and Switch': 'Guardar y cambiar',
  'Search devices': 'Buscar dispositivos', 'Select a configured space.': 'Selecciona un espacio configurado.',
  'Select a floor to open live monitoring': 'Selecciona un piso para abrir el monitoreo en vivo',
  'Select an Area': 'Selecciona un área',
  'Serial Number': 'Número de serie', 'Severity': 'Severidad', 'Signal Strength': 'Intensidad de señal',
  'Smoke Level': 'Nivel de humo', 'Snap': 'Ajuste', 'Space': 'Espacio',
  'Space already assigned': 'Espacio ya asignado', 'Space information': 'Información del espacio',
  'Spaces are configured in Floor Plan Editor': 'Los espacios se configuran en el editor del plano',
  'Table View': 'Vista de tabla', 'Target Device': 'Dispositivo objetivo',
  'This building contains:': 'Este edificio contiene:', 'Threshold crossed': 'Umbral superado',
  'Total Buildings': 'Total de edificios', 'Unassigned Spaces': 'Espacios sin asignar',
  'Unplaced': 'Sin ubicar', 'Unsaved Changes': 'Cambios sin guardar', 'Updated': 'Actualizado',
  'Upload building image': 'Subir imagen del edificio', 'Variable': 'Variable', 'Version': 'Versión',
  'View': 'Ver', 'View all': 'Ver todo', 'Weak Signal': 'Señal débil', 'Width': 'Ancho', 'Zone': 'Zona',
  'Operational Analytics': 'Analítica operativa',
  'Average readings across monitored buildings': 'Lecturas promedio de los edificios monitoreados',
  'Incidents created in the selected period': 'Incidentes creados en el período seleccionado',
  'Trends from alerts, incidents and monitored zones': 'Tendencias de alertas, incidentes y zonas monitoreadas',
  'Incident summary': 'Resumen de incidentes', 'Incident filters': 'Filtros de incidentes',
  'Incident status': 'Estado del incidente', 'Incident type': 'Tipo de incidente',
  'Loading incidents...': 'Cargando incidentes...', 'Loading incident...': 'Cargando incidente...',
  'Incidents could not be loaded': 'No se pudieron cargar los incidentes',
  'Incident could not be loaded': 'No se pudo cargar el incidente',
  'No incidents found': 'No se encontraron incidentes', 'Try changing the filters.': 'Intenta cambiar los filtros.',
  'Floor not specified': 'Piso no especificado', '← Incidents': '← Incidentes',
  'The incident was created by the operational risk flow.': 'El incidente fue creado por el flujo operativo de riesgos.',
  'Assignment is managed by Incident Management.': 'La asignación es administrada por Gestión de Incidentes.',
  'Resolution notes have not been registered yet.': 'Todavía no se han registrado notas de resolución.',
  'Describe what was verified and how the incident was resolved.': 'Describe qué se verificó y cómo se resolvió el incidente.',
  'Incident assigned to your user.': 'Incidente asignado a tu usuario.',
  'Alert summary': 'Resumen de alertas', 'Alert filters': 'Filtros de alertas',
  'Last 24 hours': 'Últimas 24 horas',
  'Last 7 days': 'Últimos 7 días', 'Last 30 days': 'Últimos 30 días',
  'Loading alerts...': 'Cargando alertas...', 'Loading alert...': 'Cargando alerta...',
  'Alerts could not be loaded': 'No se pudieron cargar las alertas',
  'Alert could not be loaded': 'No se pudo cargar la alerta', 'No alerts found': 'No se encontraron alertas',
  'Read-only risk notifications from Alert & Response Management': 'Notificaciones de riesgo de solo lectura de Gestión de Alertas y Respuestas',
  'Historical measurements provided by Risk Detection.': 'Mediciones históricas proporcionadas por Detección de Riesgos.',
  'Detection evidence is unavailable in the current data source.': 'La evidencia de detección no está disponible en la fuente de datos actual.',
  'Communication attempts associated with this alert.': 'Intentos de comunicación asociados con esta alerta.',
  'Execution lifecycle belongs to Alert & Response Management.': 'El ciclo de ejecución pertenece a Gestión de Alertas y Respuestas.',
  'Incident lifecycle belongs to Incident Management.': 'El ciclo del incidente pertenece a Gestión de Incidentes.',
  'Open Incidents →': 'Abrir incidentes →',
  'The requested alert does not exist or is unavailable.': 'La alerta solicitada no existe o no está disponible.',
  'Devices are created and positioned directly from each Floor Plan Editor.': 'Los dispositivos se crean y posicionan directamente desde cada editor de planos.',
  'Composed from Device Management, Monitoring, Connectivity and Building Management.': 'Compuesto con datos de Dispositivos, Monitoreo, Conectividad y Edificios.',
  'No description': 'Sin descripción', 'No description provided.': 'No se proporcionó una descripción.',
  'Retired devices are read-only.': 'Los dispositivos retirados son de solo lectura.',
  'Backend domain rules are also enforced by the mock adapter.': 'El adaptador de demostración también aplica las reglas del dominio.',
  'Save changes': 'Guardar cambios', 'Latest monitoring measurement': 'Última medición de monitoreo',
  'Device Management lifecycle': 'Ciclo de vida de Gestión de Dispositivos',
  'Monitoring measurements received for this physical device.': 'Mediciones de monitoreo recibidas para este dispositivo físico.',
  'Presentation reference, not part of the Device aggregate.': 'Referencia visual; no forma parte del agregado del dispositivo.',
  'One per line: code | MEASUREMENT/ACTUATION | optional unit': 'Uno por línea: código | MEDICIÓN/ACTUACIÓN | unidad opcional',
  'Create a visual plan to monitor spaces and devices on this floor.': 'Crea un plano visual para monitorear los espacios y dispositivos de este piso.',
  'Current period distribution': 'Distribución del período actual',
  'Historical measurements from Monitoring': 'Mediciones históricas de Monitoreo',
  'Details →': 'Detalles →',
  'Click any room to inspect details': 'Haz clic en cualquier sala para consultar sus detalles',
  'Copyright': 'Derechos reservados',
  'Buildings Monitored': 'Edificios monitoreados', 'View spaces →': 'Ver espacios →',
  'Live Connectivity Management status': 'Estado en vivo de la gestión de conectividad',
  'CRITICAL': 'CRÍTICO', 'WARNING': 'ADVERTENCIA', 'NORMAL': 'NORMAL', 'ACTIVE': 'ACTIVO',
  'IN_PROGRESS': 'EN PROGRESO', 'RESOLVED': 'RESUELTO', 'CLOSED': 'CERRADO',
  'Active Incidents': 'Incidentes activos', 'Avg. Resolution': 'Resolución promedio',
  'Alert & Response read model for the selected period': 'Datos de alertas y respuestas para el período seleccionado',
  'Alerts grouped by Building Management zone': 'Alertas agrupadas por zona de gestión del edificio',
  'Observed Incident Management durations': 'Duraciones observadas en la gestión de incidentes',
  'Search incidents, type or zone...': 'Buscar incidentes, tipo o zona...',
  'Alert, risk, building or zone...': 'Alerta, riesgo, edificio o zona...',
  'Search name, code, model or serial...': 'Buscar nombre, código, modelo o serie...',
  'Search rooms or spaces...': 'Buscar salas o espacios...',
  'Search buildings, addresses...': 'Buscar edificios o direcciones...',
  'Monitor every floor, space and sensor from one secure operations platform.': 'Monitorea cada piso, espacio y sensor desde una plataforma de operaciones segura.',
  'Sign in to continue to your monitoring workspace.': 'Inicia sesión para continuar a tu espacio de monitoreo.',
  'Building Name *': 'Nombre del edificio *', 'Address *': 'Dirección *',
  'Name the floors. Monitored spaces are created later in Floor Plan Editor.': 'Asigna un nombre a los pisos. Los espacios monitoreados se crean después en el editor del plano.',
  'Confirm the information before': 'Confirma la información antes de', 'saving changes': 'guardar los cambios',
  'creating the building': 'crear el edificio', 'Main Building': 'Edificio Principal',
  'Select': 'Seleccionar', 'Hallway': 'Pasadizo', 'Wall': 'Pared', 'Door': 'Puerta',
  'Stairs': 'Escaleras', 'Restroom': 'Baño', 'Pan': 'Desplazar',
  'Drag this marker directly on the canvas to move it between monitored spaces.': 'Arrastra este marcador directamente sobre el plano para moverlo entre espacios monitoreados.',
  'Click inside a monitored Area to place this Device.': 'Haz clic dentro de un área monitoreada para colocar este dispositivo.',
  'View All →': 'Ver todo →', 'Gas crossed critical threshold': 'El gas superó el umbral crítico',
  'Smoke levels increasing': 'Los niveles de humo están aumentando', 'All conditions within range': 'Todas las condiciones están dentro del rango',
  'All readings in range': 'Todas las lecturas están dentro del rango',
  'Alert is read-only; risk classification belongs to Risk Detection.': 'La alerta es de solo lectura; la clasificación del riesgo corresponde a Detección de Riesgos.',
  'Automatic': 'Automático', 'Human required': 'Requiere intervención humana', 'SUCCEEDED': 'COMPLETADO',
  'FAILED': 'FALLIDO', 'PENDING': 'PENDIENTE', 'DELIVERED': 'ENTREGADO', 'Delivered': 'Entregado',
  'REJECTED': 'RECHAZADO', 'APPROVED': 'APROBADO', 'No deliveries': 'Sin entregas',
  'Delivery Failures': 'Fallos de entrega',
  'Alert Center': 'Centro de Alertas', '← Alert Center': '← Centro de Alertas', 'Return to Alert Center': 'Volver al Centro de Alertas',
  'Resolves': 'Resuelve', 'Unassigned': 'Sin asignar', 'Unassigned zone': 'Zona sin asignar',
  'Incident creation is not exposed as a manual Web action. Assignment and resolution are the supported operator actions.': 'La creación de incidentes no está disponible como acción manual. La asignación y la resolución son las acciones permitidas para el operador.',
};

const UI_ES_CASE_INSENSITIVE = new Map(
  Object.entries(UI_ES).map(([english, spanish]) => [english.toLocaleLowerCase('en'), spanish]),
);

const PHRASES_ES: Array<[RegExp, string]> = [
  [/\bUnassigned\b/gi, 'Sin asignar'], [/\bUnknown\b/gi, 'Desconocido'], [/\bPending\b/gi, 'Pendiente'],
  [/\bFloor Plan\b/g, 'Plano'], [/\bFloor (\d+)\b/g, 'Piso $1'], [/\bRoom\b/g, 'Sala'],
  [/\bspaces\b/gi, 'espacios'], [/\bdevices\b/gi, 'dispositivos'], [/\bfloors\b/gi, 'pisos'],
  [/\balerts\b/gi, 'alertas'], [/\bincidents\b/gi, 'incidentes'], [/\bminutes ago\b/gi, 'minutos atrás'],
  [/\brecently\b/gi, 'recientemente'], [/\bconfigured\b/gi, 'configurado'], [/\bnot configured\b/gi, 'no configurado'],
  [/\bdelivered\b/gi, 'entregadas'],
  [/\bSearch ([^.]*)\.\.\./g, 'Buscar $1...'], [/\bSave ([A-Za-z ]+)/g, 'Guardar $1'],
];

@Injectable({ providedIn: 'root' })
export class LanguageService {
  readonly language = signal<AppLanguage>(this.initialLanguage());

  constructor() { this.applyDocumentLanguage(this.language()); }

  setLanguage(language: AppLanguage): void {
    this.language.set(language);
    this.applyDocumentLanguage(language);
    if (typeof localStorage !== 'undefined') localStorage.setItem('resq-language', language);
  }

  fromPreference(value?: string): AppLanguage { return value?.toLowerCase().startsWith('es') ? 'es' : 'en'; }
  toPreference(language = this.language()): 'en_US' | 'es_419' { return language === 'es' ? 'es_419' : 'en_US'; }
  t(key: string, english: string): string { return this.language() === 'es' ? (ES[key] ?? english) : english; }

  translateText(value: string): string {
    if (this.language() === 'en') return value;
    const trimmed = value.trim();
    if (!trimmed) return value;
    const normalized = trimmed.replace(/\s+/g, ' ');
    let translated = UI_ES[normalized]
      ?? UI_ES_CASE_INSENSITIVE.get(normalized.toLocaleLowerCase('en'))
      ?? normalized;
    if (translated === normalized) for (const [pattern, replacement] of PHRASES_ES) translated = translated.replace(pattern, replacement);
    return value.replace(trimmed, translated);
  }

  private initialLanguage(): AppLanguage {
    if (typeof localStorage === 'undefined') return 'en';
    return localStorage.getItem('resq-language') === 'es' ? 'es' : 'en';
  }

  private applyDocumentLanguage(language: AppLanguage): void {
    if (typeof document !== 'undefined') document.documentElement.lang = language;
  }
}
