import { ChangeDetectionStrategy, Component, OnInit, computed, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { BarChartComponent, DoughnutChartComponent, EmptyStateComponent, KpiCardComponent, LineChartComponent, LoadingStateComponent } from '../../shared/ui/ui.components';
import { AnalyticsWorkspaceFacade } from './analytics-workspace.facade';

@Component({
  selector:'resq-analytics-page',standalone:true,imports:[FormsModule,KpiCardComponent,LineChartComponent,DoughnutChartComponent,BarChartComponent,LoadingStateComponent,EmptyStateComponent],changeDetection:ChangeDetectionStrategy.OnPush,
  template:`
    <div class="period"><span>Analysis period</span>@for(item of periods;track item.value){<button type="button" [class.active]="period()===item.value" (click)="period.set(item.value)">{{item.label}}</button>}</div>
    @if(workspace.loading()){<resq-loading-state message="Building analytics from bounded-context data..." />}@else if(workspace.error()){<resq-empty-state title="Analytics could not be loaded" [message]="workspace.error()!.message" />}@else{
      <section class="kpis"><resq-kpi-card icon="△" [value]="filteredAlerts().length" label="Total Alerts" tone="red"/><resq-kpi-card icon="◷" [value]="filteredIncidents().length" label="Total Incidents" tone="amber"/><resq-kpi-card icon="✓" [value]="averageResolution()" label="Avg. Resolution Time" tone="green"/><resq-kpi-card icon="◉" [value]="uptime()" label="Device Online Rate"/></section>
      <section class="chart-grid">
        <article class="wide"><header><div><h3>Alerts Over Time</h3><p>Alert & Response read model for the selected period</p></div></header><resq-line-chart [labels]="alertTimeLabels()" [values]="alertTimeValues()" datasetLabel="Alerts" /></article>
        <article><header><div><h3>Alerts by Severity</h3><p>Current period distribution</p></div></header><div class="donut"><resq-doughnut-chart [labels]="['Critical','Warning','Info']" [values]="[criticalAlerts(),warningAlerts(),infoAlerts()]" [centerValue]="filteredAlerts().length" centerLabel="Alerts"/><ul><li><i class="critical"></i>Critical <b>{{criticalAlerts()}}</b></li><li><i class="warning"></i>Warning <b>{{warningAlerts()}}</b></li><li><i class="info"></i>Info <b>{{infoAlerts()}}</b></li></ul></div></article>
        <article><header><div><h3>Most Affected Zones</h3><p>Alerts grouped by Building Management zone</p></div></header><resq-bar-chart [labels]="affectedZoneLabels()" [values]="affectedZoneValues()" color="#f04438"/></article>
        <article><header><div><h3>Devices by Connectivity</h3><p>Live Connectivity Management status</p></div></header><div class="donut"><resq-doughnut-chart [labels]="['Online','Weak Signal','Offline / Timeout']" [values]="[onlineDevices(),weakDevices(),offlineDevices()]" [centerValue]="workspace.devices().length" centerLabel="Devices"/><ul><li><i class="normal"></i>Online <b>{{onlineDevices()}}</b></li><li><i class="warning"></i>Weak Signal <b>{{weakDevices()}}</b></li><li><i class="offline"></i>Offline / Timeout <b>{{offlineDevices()}}</b></li></ul></div></article>
        <article class="wide"><header><div><h3>Monitoring Measurements</h3><p>Historical measurements from Monitoring</p></div><select [(ngModel)]="metric"><option value="">All variables</option>@for(item of metrics();track item){<option [value]="item">{{item}}</option>}</select></header>@if(environmentalValues().length){<resq-line-chart [labels]="environmentalLabels()" [values]="environmentalValues()" [datasetLabel]="metric || 'Measurement'" [unit]="environmentalUnit()"/>}@else{<resq-empty-state title="No measurements in period" message="Choose another period or variable." />}</article>
        <article><header><div><h3>Incidents Over Time</h3><p>Incidents created in the selected period</p></div></header><resq-bar-chart [labels]="incidentTimeLabels()" [values]="incidentTimeValues()"/></article>
        <article><header><div><h3>Resolution Performance</h3><p>Observed Incident Management durations</p></div></header><div class="performance"><div><span>Resolved incidents</span><b>{{resolvedCount()}}</b><em [style.--w]="resolvedBarWidth()"></em></div><div><span>In progress</span><b>{{inProgressCount()}}</b><em [style.--w]="inProgressBarWidth()"></em></div><div><span>Active</span><b>{{activeCount()}}</b><em [style.--w]="activeBarWidth()"></em></div></div></article>
      </section>
    }
  `,styleUrl:'./analytics.page.scss'
})
export class AnalyticsPage implements OnInit{
  readonly workspace=inject(AnalyticsWorkspaceFacade);readonly period=signal<'24h'|'7d'|'30d'>('7d');metric='';readonly periods=[{value:'24h' as const,label:'Last 24 Hours'},{value:'7d' as const,label:'Last 7 Days'},{value:'30d' as const,label:'Last 30 Days'}];
  readonly filteredAlerts=computed(()=>{const cutoff=this.cutoff();return this.workspace.alerts().filter(item=>item.generatedAt>=cutoff);});readonly filteredIncidents=computed(()=>{const cutoff=this.cutoff();return this.workspace.incidents().filter(item=>item.incident.createdAt>=cutoff);});readonly metrics=computed(()=>[...new Set(this.workspace.measurements().map(item=>item.variableType))].sort());
  ngOnInit():void{this.workspace.load().subscribe({error:()=>undefined});}
  criticalAlerts():number{return this.filteredAlerts().filter(item=>item.severity.toLowerCase()==='critical').length;}warningAlerts():number{return this.filteredAlerts().filter(item=>item.severity.toLowerCase()==='warning').length;}infoAlerts():number{return this.filteredAlerts().filter(item=>item.severity.toLowerCase()==='info').length;}
  onlineDevices():number{return this.workspace.devices().filter(row=>row.connection?.status==='ONLINE').length;}weakDevices():number{return this.workspace.devices().filter(row=>row.connection?.status==='ONLINE'&&row.connection.signalStrength!==undefined&&row.connection.signalStrength<-75).length;}offlineDevices():number{return this.workspace.devices().filter(row=>row.connection?.status!=='ONLINE').length;}uptime():string{const total=this.workspace.devices().length;return total?`${((this.onlineDevices()/total)*100).toFixed(1)}%`:'—';}
  averageResolution():string{const values=this.filteredIncidents().filter(row=>row.incident.resolvedAt).map(row=>row.incident.resolvedAt!.getTime()-row.incident.createdAt.getTime());if(!values.length)return'—';const minutes=Math.round(values.reduce((sum,value)=>sum+value,0)/values.length/60000);return minutes>=60?`${(minutes/60).toFixed(1)} h`:`${minutes} min`;}
  affectedZoneLabels():string[]{return this.zoneDistribution().map(item=>item[0]);}affectedZoneValues():number[]{return this.zoneDistribution().map(item=>item[1]);}
  alertTimeLabels():string[]{return this.timeBuckets(this.filteredAlerts().map(item=>item.generatedAt)).labels;}alertTimeValues():number[]{return this.timeBuckets(this.filteredAlerts().map(item=>item.generatedAt)).values;}
  incidentTimeLabels():string[]{return this.timeBuckets(this.filteredIncidents().map(item=>item.incident.createdAt)).labels;}incidentTimeValues():number[]{return this.timeBuckets(this.filteredIncidents().map(item=>item.incident.createdAt)).values;}
  environmentalLabels():string[]{return this.environmentalSeries().map(item=>item.measuredAt.toLocaleString([],{month:'short',day:'2-digit',hour:'2-digit',minute:'2-digit'}));}environmentalValues():number[]{return this.environmentalSeries().map(item=>item.measurementValue.value);}environmentalUnit():string{return this.environmentalSeries()[0]?.measurementValue.unit??'';}
  resolvedCount():number{return this.filteredIncidents().filter(row=>row.incident.status==='RESOLVED'||row.incident.status==='CLOSED').length;}inProgressCount():number{return this.filteredIncidents().filter(row=>row.incident.status==='IN_PROGRESS').length;}activeCount():number{return this.filteredIncidents().filter(row=>row.incident.status==='ACTIVE').length;}resolvedBarWidth():string{return this.barWidth(this.resolvedCount());}inProgressBarWidth():string{return this.barWidth(this.inProgressCount());}activeBarWidth():string{return this.barWidth(this.activeCount());}
  private cutoff():Date{const days=this.period()==='24h'?1:this.period()==='7d'?7:30;return new Date(Date.now()-days*86400000);}private zoneDistribution():Array<[string,number]>{const map=new Map<string,number>();this.filteredAlerts().forEach(item=>map.set(item.location.zoneName,(map.get(item.location.zoneName)??0)+1));return [...map].sort((a,b)=>b[1]-a[1]).slice(0,5);}private timeBuckets(dates:Date[]):{labels:string[];values:number[]}{const map=new Map<string,number>();dates.forEach(date=>{const key=this.period()==='24h'?date.toLocaleTimeString([],{hour:'2-digit'}):date.toLocaleDateString([],{month:'short',day:'2-digit'});map.set(key,(map.get(key)??0)+1);});const entries=[...map];return{labels:entries.map(item=>item[0]),values:entries.map(item=>item[1])};}private environmentalSeries(){const cutoff=this.cutoff();return this.workspace.measurements().filter(item=>item.measuredAt>=cutoff&&(!this.metric||item.variableType===this.metric)).sort((a,b)=>a.measuredAt.getTime()-b.measuredAt.getTime()).slice(-30);}private barWidth(value:number):string{const total=Math.max(1,this.filteredIncidents().length);return`${Math.round((value/total)*100)}%`;}
}
