import { ChangeDetectionStrategy, Component, OnInit, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { ActivatedRoute, RouterLink } from '@angular/router';
import { Incident, IncidentStatus } from '../../core/models/resq.models';
import { ALERTS, BUILDINGS, FLOORS, INCIDENTS, SPACES } from '../../core/mock-data/resq.mock';
import { IncidentService } from '../../core/services/data.services';
import { KpiCardComponent, StatusBadgeComponent } from '../../shared/ui/ui.components';

@Component({selector:'resq-incidents-page',standalone:true,imports:[FormsModule,RouterLink,KpiCardComponent,StatusBadgeComponent],changeDetection:ChangeDetectionStrategy.OnPush,template:`<section class="kpis"><resq-kpi-card icon="◷" [value]="count('Open')" label="Open Incidents" tone="red"/><resq-kpi-card icon="↻" [value]="count('InProgress')" label="In Progress" tone="amber"/><resq-kpi-card icon="✓" [value]="count('Resolved')" label="Resolved" tone="green"/><resq-kpi-card icon="◴" value="42 min" label="Average Resolution"/></section><div class="filters"><label>⌕<input [(ngModel)]="query" (ngModelChange)="apply()" placeholder="Search incidents..."/></label><select [(ngModel)]="status" (ngModelChange)="apply()"><option value="">All statuses</option><option value="Open">Open</option><option value="InProgress">In Progress</option><option value="Resolved">Resolved</option></select><select><option>All severities</option><option>Critical</option><option>Warning</option></select></div><div class="incident-grid">@for(incident of filtered();track incident.id){<article><div class="card-head"><span [class]="'severity '+incident.severity.toLowerCase()">{{incident.severity}}</span><resq-status-badge [status]="incident.status"/></div><a [routerLink]="'/incidents/'+incident.id"><h3>{{incident.title}}</h3><p>{{incident.description}}</p></a><div class="meta"><span>⌖ {{location(incident)}}</span><span>◷ {{age(incident.createdAt)}}</span><span>△ {{incident.alertIds.length}} related alert</span></div><footer><b>{{incident.id}}</b><div>@if(incident.status==='Open'){<button (click)="change(incident,'InProgress')">Start investigation</button>}@if(incident.status==='InProgress'){<button (click)="change(incident,'Resolved')">Resolve</button>}<a [routerLink]="'/incidents/'+incident.id">Details →</a></div></footer></article>}</div>`,styleUrl:'./incidents.pages.scss'})
export class IncidentsPage {readonly filtered=signal(INCIDENTS);query='';status='';constructor(private readonly service:IncidentService){}count(s:IncidentStatus){return INCIDENTS.filter(i=>i.status===s).length}apply():void{const q=this.query.toLowerCase();this.filtered.set(INCIDENTS.filter(i=>(!q||`${i.id} ${i.title}`.toLowerCase().includes(q))&&(!this.status||i.status===this.status)))}location(i:Incident){const s=SPACES.find(x=>x.id===i.spaceId);return `${s?.name??'Space'} · Room ${s?.roomNumber??'—'}`}age(d:Date){const h=Math.max(1,Math.round((Date.now()-d.getTime())/3600000));return `${h}h ago`}change(i:Incident,status:IncidentStatus):void{this.service.updateStatus(i.id,status);this.filtered.update(items=>items.map(item=>item.id===i.id?{...item,status,resolvedAt:status==='Resolved'?new Date():undefined}:item))}}

@Component({selector:'resq-incident-detail',standalone:true,imports:[RouterLink,StatusBadgeComponent],changeDetection:ChangeDetectionStrategy.OnPush,template:`@if(incident()){<div class="detail-head"><div><a routerLink="/incidents">← Incidents</a><p>{{incident()!.id}}</p><h2>{{incident()!.title}}</h2><span>{{incident()!.description}}</span></div><div><resq-status-badge [status]="incident()!.severity"/><resq-status-badge [status]="incident()!.status"/></div></div><div class="actions">@if(incident()!.status==='Open'){<button (click)="change('InProgress')">Start Investigation</button>}@if(incident()!.status==='InProgress'){<button (click)="change('Resolved')">Mark as Resolved</button>}@if(incident()!.status==='Resolved'){<button disabled>✓ Incident Resolved</button>}</div><div class="grid"><article><h3>Incident Timeline</h3><div class="timeline"><div class="done"><i>✓</i><section><b>Condition detected</b><small>{{incident()!.createdAt.toLocaleString()}}</small><p>A sensor reading crossed its configured safety threshold.</p></section></div><div class="done"><i>✓</i><section><b>Alert generated</b><small>Immediately after detection</small><p>ResQ created and routed the alert to the response team.</p></section></div><div [class.done]="incident()!.status!=='Open'"><i>{{incident()!.status!=='Open'?'✓':'3'}}</i><section><b>Investigation</b><small>Facilities response</small><p>Site conditions and affected equipment are being reviewed.</p></section></div><div [class.done]="incident()!.status==='Resolved'"><i>{{incident()!.status==='Resolved'?'✓':'4'}}</i><section><b>Resolved</b><small>{{incident()!.resolvedAt?.toLocaleString()||'Pending'}}</small><p>The incident is closed when all conditions return to a safe state.</p></section></div></div><h3>Response Notes</h3><div class="note"><b>Facilities Team</b><small>Today, 14:46</small><p>Ventilation checked. Area secured while readings stabilize.</p></div></article><aside><h3>Location</h3><dl><dt>Building</dt><dd>{{buildingName()}}</dd><dt>Floor</dt><dd>{{floorName()}}</dd><dt>Space</dt><dd><a [routerLink]="'/spaces/'+incident()!.spaceId">{{space()?.name}}</a></dd><dt>Room</dt><dd>{{space()?.roomNumber}}</dd><dt>Created</dt><dd>{{incident()!.createdAt.toLocaleString()}}</dd><dt>Resolved</dt><dd>{{incident()!.resolvedAt?.toLocaleString()||'—'}}</dd></dl><h3>Related Alerts</h3>@for(alert of alerts();track alert.id){<a class="alert" [routerLink]="'/alerts/'+alert.id"><span>!</span><div><b>{{alert.title}}</b><small>{{alert.id}} · {{alert.status}}</small></div>→</a>}</aside></div>}@else{<div class="not-found"><h2>Incident not found</h2><a routerLink="/dashboard">Back to Dashboard</a></div>}`,styleUrl:'./incident-detail.page.scss'})
export class IncidentDetailPage implements OnInit {readonly incident=signal<Incident|undefined>(undefined);constructor(private readonly route:ActivatedRoute,private readonly service:IncidentService){}ngOnInit():void{this.incident.set(INCIDENTS.find(i=>i.id===this.route.snapshot.paramMap.get('incidentId')))}change(status:IncidentStatus):void{const i=this.incident();if(i){this.service.updateStatus(i.id,status);this.incident.set({...i,status,resolvedAt:status==='Resolved'?new Date():undefined})}}space(){return SPACES.find(s=>s.id===this.incident()?.spaceId)}floorName(){return FLOORS.find(f=>f.id===this.incident()?.floorId)?.name??'—'}buildingName(){return BUILDINGS.find(b=>b.id===this.incident()?.buildingId)?.name??'—'}alerts(){return ALERTS.filter(a=>this.incident()?.alertIds.includes(a.id))}}
