import { ChangeDetectionStrategy, Component, OnInit, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { ActivatedRoute, Router, RouterLink } from '@angular/router';
import { Building } from '../../core/models/resq.models';
import { BUILDINGS, DEVICES } from '../../core/mock-data/resq.mock';
import { KpiCardComponent, StatusBadgeComponent } from '../../shared/ui/ui.components';

@Component({
  selector:'resq-buildings-page',standalone:true,imports:[FormsModule,RouterLink,StatusBadgeComponent],changeDetection:ChangeDetectionStrategy.OnPush,
  template:`<div class="toolbar"><div><h2>Building Portfolio</h2><p>{{filtered().length}} properties connected to ResQ</p></div><label>⌕ <input placeholder="Search buildings..." [(ngModel)]="query" (ngModelChange)="filter()"/></label></div><div class="building-grid">@for(building of filtered();track building.id){<article><div class="building-image"><svg viewBox="0 0 260 120"><path d="M40 90l90-45 90 45-90 25z"/><path d="M55 68l75-38 75 38-75 23z"/><path d="M70 48l60-30 60 30-60 20z"/><path class="lines" d="M55 68v22m150-22v22M70 48v20m120-20v20"/></svg><resq-status-badge [status]="building.status"/></div><div class="building-body"><h3>{{building.name}}</h3><p>⌖ {{building.address}}</p><div class="stats"><span><b>{{building.floors.length}}</b>Floors</span><span><b>{{spaceCount(building)}}</b>Spaces</span><span><b>{{deviceCount(building)}}</b>Devices</span><span><b>{{building.id==='science'?12:building.id==='main'?4:1}}</b>Alerts</span></div><a [routerLink]="'/buildings/'+building.id">View Building <span>→</span></a></div></article>}</div>`,
  styles:[`:host{display:block}.toolbar{display:flex;justify-content:space-between;align-items:center;margin:5px 0 14px}.toolbar h2{margin:0;font-size:17px}.toolbar p{margin:4px 0 0;color:#98a2b3;font-size:11px}.toolbar label{width:260px;height:38px;background:#fff;border:1px solid var(--resq-border);border-radius:7px;display:flex;align-items:center;padding:0 11px;gap:7px}.toolbar input{border:0;outline:0;width:100%}.building-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:13px}.building-grid article{background:#fff;border:1px solid var(--resq-border);border-radius:11px;overflow:hidden}.building-image{height:145px;background:linear-gradient(145deg,#edf4fb,#f7fafc);position:relative;display:grid;place-items:center}.building-image svg{width:78%;height:100%}.building-image path{fill:#dce6f0;stroke:#7890a7}.building-image path:nth-child(2){fill:#cfe0f3}.building-image .lines{fill:none}.building-image resq-status-badge{position:absolute;top:12px;right:12px}.building-body{padding:15px}.building-body h3{margin:0;font-size:15px}.building-body p{font-size:10px;color:#667085}.stats{display:grid;grid-template-columns:repeat(4,1fr);margin:15px 0;border-block:1px solid #f2f4f7;padding:12px 0}.stats span{font-size:8px;color:#98a2b3;text-align:center;border-right:1px solid #f2f4f7}.stats span:last-child{border:0}.stats b{display:block;font-size:14px;color:#344054;margin-bottom:3px}.building-body>a{display:flex;justify-content:space-between;color:#1570ef;text-decoration:none;font-size:10px;font-weight:700}@media(max-width:960px){.building-grid{grid-template-columns:1fr 1fr}}@media(max-width:620px){.toolbar{align-items:flex-start;gap:12px;flex-direction:column}.toolbar label{width:calc(100% - 24px)}.building-grid{grid-template-columns:1fr}}`]
})
export class BuildingsPage { query='';readonly filtered=signal(BUILDINGS);filter():void{const q=this.query.toLowerCase();this.filtered.set(BUILDINGS.filter(item=>`${item.name} ${item.address}`.toLowerCase().includes(q)))}spaceCount(building:Building):number{return building.floors.reduce((sum,floor)=>sum+floor.spaces.length,0)}deviceCount(building:Building):number{const ids=new Set(building.floors.flatMap(floor=>floor.spaces.map(space=>space.id)));return DEVICES.filter(device=>ids.has(device.spaceId)).length}}

@Component({
  selector:'resq-building-detail',standalone:true,imports:[RouterLink,KpiCardComponent,StatusBadgeComponent],changeDetection:ChangeDetectionStrategy.OnPush,
  template:`@if(building()){<div class="detail-head"><div><a routerLink="/buildings">← Buildings</a><h2>{{building()!.name}}</h2><p>⌖ {{building()!.address}} · {{building()!.description}}</p></div><resq-status-badge [status]="building()!.status"/></div><section class="kpis"><resq-kpi-card icon="▱" [value]="building()!.floors.length" label="Floors"/><resq-kpi-card icon="⌂" [value]="spaces()" label="Monitored Spaces" tone="green"/><resq-kpi-card icon="◉" [value]="devices()" label="Connected Devices"/><resq-kpi-card icon="△" [value]="12" label="Active Alerts" tone="red"/></section><article class="overview"><div><h3>Building Overview</h3><p>Select a floor to open live monitoring</p></div><div class="stack">@for(floor of reversedFloors();track floor.id;let i=$index){<button [class]="'floor '+floor.status.toLowerCase()" (click)="openFloor(floor.id)" [style.--i]="i"><span class="slab"><b>{{floor.name}}</b><small>{{floor.spaces.length}} spaces · {{floor.status}}</small></span><em>{{floor.level}}</em></button>}</div><div class="floor-summary">@for(floor of building()!.floors;track floor.id){<button (click)="openFloor(floor.id)"><span>Floor {{floor.level}}</span><small>{{floor.spaces.length}} spaces</small><resq-status-badge [status]="floor.status"/>→</button>}</div></article>}@else{<div class="not-found"><h2>Building not found</h2><a routerLink="/dashboard">Back to Dashboard</a></div>}`,
  styles:[`:host{display:block}.detail-head{display:flex;justify-content:space-between;align-items:center;margin:4px 2px 14px}.detail-head a{font-size:10px;color:#1570ef;text-decoration:none}.detail-head h2{margin:7px 0 4px;font-size:20px}.detail-head p{margin:0;color:#667085;font-size:11px}.kpis{display:grid;grid-template-columns:repeat(4,1fr);gap:10px}.overview{margin-top:11px;background:#fff;border:1px solid var(--resq-border);border-radius:11px;padding:18px;display:grid;grid-template-columns:1fr 2fr 1fr;min-height:500px}.overview h3{font-size:15px;margin:0}.overview p{font-size:10px;color:#98a2b3}.stack{position:relative;min-height:430px;perspective:1000px;display:flex;flex-direction:column;align-items:center;justify-content:center}.floor{border:0;background:transparent;width:370px;height:85px;position:relative;margin:-9px 0;transform:rotateX(58deg) rotateZ(-25deg);cursor:pointer;transition:.2s;z-index:calc(10 - var(--i))}.floor:hover{transform:rotateX(58deg) rotateZ(-25deg) translateZ(25px) translateY(-10px)}.slab{position:absolute;inset:0;background:linear-gradient(135deg,#edf2f7,#cfd9e4);border:1px solid #91a4b8;box-shadow:-8px 12px 15px #1d355727;display:grid;place-content:center;text-align:center}.floor.warning .slab{border:2px solid #fdb022}.floor.critical .slab{border:2px solid #f04438}.slab b{font-size:12px}.slab small{font-size:8px;color:#667085;margin-top:3px}.floor>em{position:absolute;right:-42px;top:28px;transform:rotateZ(25deg) rotateX(-58deg);background:#1570ef;color:#fff;border-radius:50%;width:26px;height:26px;display:grid;place-items:center;font-style:normal}.floor-summary{display:flex;flex-direction:column;justify-content:center;gap:8px}.floor-summary>button{display:grid;grid-template-columns:1fr auto 15px;align-items:center;text-align:left;border:1px solid var(--resq-border);background:#fff;border-radius:7px;padding:10px;cursor:pointer}.floor-summary span,.floor-summary small{display:block}.floor-summary span{font-size:11px;font-weight:700}.floor-summary small{font-size:8px;color:#98a2b3}.not-found{text-align:center;padding:80px}.not-found a{color:#1570ef}@media(max-width:1000px){.overview{grid-template-columns:1fr 1.5fr}.floor-summary{grid-column:1/-1;display:grid;grid-template-columns:1fr 1fr}.kpis{grid-template-columns:1fr 1fr}}@media(max-width:650px){.overview{grid-template-columns:1fr}.stack{transform:scale(.75);margin:-50px}.floor-summary{grid-template-columns:1fr}.kpis{grid-template-columns:1fr}.detail-head p{max-width:280px}}`]
})
export class BuildingDetailPage implements OnInit {readonly building=signal<Building|undefined>(undefined);constructor(private readonly route:ActivatedRoute,private readonly router:Router){}ngOnInit():void{this.building.set(BUILDINGS.find(item=>item.id===this.route.snapshot.paramMap.get('buildingId')))}spaces():number{return this.building()?.floors.flatMap(f=>f.spaces).length??0}devices():number{const ids=new Set(this.building()?.floors.flatMap(f=>f.spaces.map(s=>s.id))??[]);return DEVICES.filter(d=>ids.has(d.spaceId)).length}reversedFloors(){return [...(this.building()?.floors??[])].reverse()}openFloor(floorId:string):void{this.router.navigate(['/monitoring',this.building()?.id,'floors',floorId])}}
