import { ChangeDetectionStrategy, Component, OnInit, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { ActivatedRoute, RouterLink } from '@angular/router';
import { Alert } from '../../core/models/resq.models';
import { ALERTS, BUILDINGS, DEVICES, FLOORS, INCIDENTS, SPACES } from '../../core/mock-data/resq.mock';
import { AlertService } from '../../core/services/data.services';
import { KpiCardComponent, StatusBadgeComponent } from '../../shared/ui/ui.components';

@Component({selector:'resq-alerts-page',standalone:true,imports:[FormsModule,RouterLink,KpiCardComponent,StatusBadgeComponent],changeDetection:ChangeDetectionStrategy.OnPush,template:`<section class="kpis"><resq-kpi-card icon="!" [value]="critical" label="Critical" tone="red"/><resq-kpi-card icon="△" [value]="warning" label="Warning" tone="amber"/><resq-kpi-card icon="✓" [value]="acknowledged" label="Acknowledged"/><resq-kpi-card icon="✓" [value]="resolved" label="Resolved Today" tone="green"/></section><div class="filters"><label>⌕<input [(ngModel)]="query" (ngModelChange)="apply()" placeholder="Search alerts..."/></label><select [(ngModel)]="severity" (ngModelChange)="apply()"><option value="">All severities</option><option>Critical</option><option>Warning</option><option>Info</option></select><select [(ngModel)]="status" (ngModelChange)="apply()"><option value="">All statuses</option><option>New</option><option>Acknowledged</option><option>Resolved</option></select><select><option>All buildings</option>@for(b of buildings;track b.id){<option>{{b.name}}</option>}</select></div><div class="table"><table><thead><tr><th>Severity</th><th>Alert</th><th>Building</th><th>Floor</th><th>Space</th><th>Device</th><th>Time</th><th>Status</th><th></th></tr></thead><tbody>@for(alert of filtered();track alert.id){<tr [routerLink]="'/alerts/'+alert.id"><td><span [class]="'severity '+alert.severity.toLowerCase()">{{alert.severity==='Critical'?'!':alert.severity==='Warning'?'△':'i'}} {{alert.severity}}</span></td><td><b>{{alert.title}}</b><small>{{alert.description}}</small></td><td>{{buildingName(alert)}}</td><td>{{floorName(alert)}}</td><td>{{spaceName(alert)}}</td><td>{{deviceCode(alert)}}</td><td>{{time(alert.timestamp)}}</td><td><resq-status-badge [status]="alert.status"/></td><td>›</td></tr>}</tbody></table></div>`,styleUrl:'./alerts.pages.scss'})
export class AlertsPage {readonly buildings=BUILDINGS;readonly filtered=signal(ALERTS);query='';severity='';status='';readonly critical=ALERTS.filter(a=>a.severity==='Critical'&&a.status!=='Resolved').length;readonly warning=ALERTS.filter(a=>a.severity==='Warning'&&a.status!=='Resolved').length;readonly acknowledged=ALERTS.filter(a=>a.status==='Acknowledged').length;readonly resolved=ALERTS.filter(a=>a.status==='Resolved').length;apply():void{const q=this.query.toLowerCase();this.filtered.set(ALERTS.filter(a=>(!q||`${a.title} ${a.description}`.toLowerCase().includes(q))&&(!this.severity||a.severity===this.severity)&&(!this.status||a.status===this.status)))}space(alert:Alert){return SPACES.find(s=>s.id===alert.spaceId)}spaceName(a:Alert){return this.space(a)?.name??'—'}floorName(a:Alert){return FLOORS.find(f=>f.id===a.floorId)?.name??'—'}buildingName(a:Alert){return BUILDINGS.find(b=>b.id===a.buildingId)?.name??'—'}deviceCode(a:Alert){return DEVICES.find(d=>d.id===a.deviceId)?.code??'—'}time(d:Date){const m=Math.round((Date.now()-d.getTime())/60000);return m<60?`${m} min ago`:`${Math.round(m/60)}h ago`}}

@Component({selector:'resq-alert-detail',standalone:true,imports:[RouterLink,StatusBadgeComponent],changeDetection:ChangeDetectionStrategy.OnPush,template:`@if(alert()){<div class="detail-head"><div><a routerLink="/alerts">← Alert Center</a><div><span [class]="alert()!.severity.toLowerCase()">!</span><div><h2>{{alert()!.title}}</h2><p>{{alert()!.id}} · Detected {{time()}}</p></div></div></div><resq-status-badge [status]="alert()!.status"/></div><div class="actions"><button [disabled]="alert()!.status!=='New'" (click)="update('Acknowledged')">✓ Acknowledge</button><button class="resolve" [disabled]="alert()!.status==='Resolved'" (click)="update('Resolved')">Resolve Alert</button></div><div class="detail-grid"><article><h3>Alert Details</h3><p class="description">{{alert()!.description}}</p><dl><dt>Severity</dt><dd><resq-status-badge [status]="alert()!.severity"/></dd><dt>Timestamp</dt><dd>{{alert()!.timestamp.toLocaleString()}}</dd><dt>Device</dt><dd><a [routerLink]="'/devices/'+alert()!.deviceId">{{device()?.name||'System evaluation'}}</a></dd><dt>Space</dt><dd><a [routerLink]="'/spaces/'+alert()!.spaceId">{{space()?.name}} · Room {{space()?.roomNumber}}</a></dd><dt>Floor</dt><dd>{{floorName()}}</dd><dt>Building</dt><dd>{{buildingName()}}</dd></dl><h3>Current Readings</h3><div class="readings">@for(d of space()?.devices?.slice(0,3)||[];track d.id){<div><span>{{d.type}}</span><b>{{d.readings.at(-1)?.value}} {{d.readings.at(-1)?.unit}}</b><resq-status-badge [status]="d.status"/></div>}</div></article><aside><h3>Response Timeline</h3><div class="timeline"><p class="done"><i></i><b>Alert detected</b><small>Automated threshold evaluation</small></p><p [class.done]="alert()!.status!=='New'"><i></i><b>Acknowledged</b><small>Awaiting operator response</small></p><p [class.done]="alert()!.status==='Resolved'"><i></i><b>Resolved</b><small>Condition returned to safe range</small></p></div>@if(incident()){<h3>Related Incident</h3><a class="incident" [routerLink]="'/incidents/'+incident()!.id"><span>◷</span><div><b>{{incident()!.title}}</b><small>{{incident()!.id}} · {{incident()!.status}}</small></div>→</a>}</aside></div>}@else{<div class="not-found"><h2>Alert not found</h2><a routerLink="/dashboard">Back to Dashboard</a></div>}`,styleUrl:'./alert-detail.page.scss'})
export class AlertDetailPage implements OnInit {readonly alert=signal<Alert|undefined>(undefined);constructor(private readonly route:ActivatedRoute,private readonly service:AlertService){}ngOnInit():void{this.alert.set(ALERTS.find(a=>a.id===this.route.snapshot.paramMap.get('alertId')))}update(status:Alert['status']){const a=this.alert();if(a){this.service.updateStatus(a.id,status);this.alert.set({...a,status})}}space(){return SPACES.find(s=>s.id===this.alert()?.spaceId)}device(){return DEVICES.find(d=>d.id===this.alert()?.deviceId)}floorName(){return FLOORS.find(f=>f.id===this.alert()?.floorId)?.name??'—'}buildingName(){return BUILDINGS.find(b=>b.id===this.alert()?.buildingId)?.name??'—'}incident(){return INCIDENTS.find(i=>i.alertIds.includes(this.alert()?.id??''))}time(){const d=this.alert()?.timestamp;return d?d.toLocaleString():'—'}}
