import { ChangeDetectionStrategy, Component, inject, OnInit, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { FormsModule } from '@angular/forms';
import { ActivatedRoute, RouterLink } from '@angular/router';
import { MatSnackBar } from '@angular/material/snack-bar';
import { Space, SpaceThresholds } from '../../core/models/resq.models';
import { ALERTS, BUILDINGS, FLOORS, SPACES } from '../../core/mock-data/resq.mock';
import { SpaceService } from '../../core/services/data.services';
import { LineChartComponent, StatusBadgeComponent } from '../../shared/ui/ui.components';

@Component({selector:'resq-spaces-page',standalone:true,imports:[CommonModule,FormsModule,RouterLink,StatusBadgeComponent],changeDetection:ChangeDetectionStrategy.OnPush,template:`
  <div class="filters"><label class="search">⌕ <input [(ngModel)]="query" (ngModelChange)="apply()" placeholder="Search rooms or spaces..."/></label><select [(ngModel)]="building" (ngModelChange)="apply()"><option value="">All buildings</option>@for(item of buildings;track item.id){<option [value]="item.id">{{item.name}}</option>}</select><select [(ngModel)]="type" (ngModelChange)="apply()"><option value="">All types</option>@for(item of types;track item){<option>{{item}}</option>}</select><select [(ngModel)]="risk" (ngModelChange)="apply()"><option value="">All risk levels</option><option>Normal</option><option>Warning</option><option>Critical</option><option>Offline</option></select><div class="views"><button [class.active]="view()==='cards'" (click)="view.set('cards')">▦</button><button [class.active]="view()==='table'" (click)="view.set('table')">☷</button></div></div>
  <div class="result-count"><b>{{filtered().length}} spaces</b><span>Live data updated moments ago</span></div>
  @if(view()==='cards'){<div class="space-grid">@for(space of filtered();track space.id){<a [routerLink]="'/spaces/'+space.id"><div class="card-head"><span class="type-icon">{{icon(space)}}</span><resq-status-badge [status]="space.status"/></div><h3>{{space.name}}</h3><p>Room {{space.roomNumber||'—'}} · {{space.type}}</p><div class="location">▥ {{buildingName(space.buildingId)}} <span>›</span> {{floorName(space.floorId)}}</div><div class="space-stats"><span><b>{{space.devices.length}}</b>Devices</span><span><b>{{space.sensitivity}}</b>Sensitivity</span><span><b>{{alertCount(space.id)}}</b>Alerts</span></div><footer>Open space details <span>→</span></footer></a>}</div>}@else{<div class="table-wrap"><table><thead><tr><th>Space</th><th>Type</th><th>Building</th><th>Floor</th><th>Sensitivity</th><th>Risk</th><th>Devices</th><th>Last Alert</th></tr></thead><tbody>@for(space of filtered();track space.id){<tr [routerLink]="'/spaces/'+space.id"><td><b>{{space.name}}</b><small>Room {{space.roomNumber}}</small></td><td>{{space.type}}</td><td>{{buildingName(space.buildingId)}}</td><td>{{floorName(space.floorId)}}</td><td>{{space.sensitivity}}</td><td><resq-status-badge [status]="space.status"/></td><td>{{space.devices.length}}</td><td>{{alertCount(space.id)}} active</td></tr>}</tbody></table></div>}
`,styleUrl:'./spaces.pages.scss'})
export class SpacesPage {readonly buildings=BUILDINGS;readonly types=['Laboratory','Classroom','Office','ServerRoom','Storage','Hallway'];readonly filtered=signal(SPACES);readonly view=signal<'cards'|'table'>('cards');query='';building='';type='';risk='';apply():void{const q=this.query.toLowerCase();this.filtered.set(SPACES.filter(s=>(!q||`${s.name} ${s.roomNumber}`.toLowerCase().includes(q))&&(!this.building||s.buildingId===this.building)&&(!this.type||s.type===this.type)&&(!this.risk||s.status===this.risk)))}icon(space:Space):string{return space.type==='Laboratory'?'⚗':space.type==='ServerRoom'?'▤':space.type==='Classroom'?'▥':'⌂'}buildingName(id:string){return BUILDINGS.find(b=>b.id===id)?.name??'—'}floorName(id:string){return FLOORS.find(f=>f.id===id)?.name??'—'}alertCount(id:string){return ALERTS.filter(a=>a.spaceId===id&&a.status!=='Resolved').length}}

@Component({selector:'resq-space-detail',standalone:true,imports:[CommonModule,ReactiveFormsModule,RouterLink,StatusBadgeComponent,LineChartComponent],changeDetection:ChangeDetectionStrategy.OnPush,template:`
  @if(space()){<div class="detail-head"><div><a routerLink="/spaces">← Spaces</a><div class="title"><span>{{space()!.type==='Laboratory'?'⚗':'⌂'}}</span><div><h2>{{space()!.name}}</h2><p>Room {{space()!.roomNumber}} · {{buildingName()}} · {{floorName()}}</p></div></div></div><resq-status-badge [status]="space()!.status"/></div><nav class="tabs">@for(item of ['Overview','Devices','Alerts','Monitoring Configuration','History'];track item){<button [class.active]="tab()===item" (click)="tab.set(item)">{{item}}</button>}</nav>
    @if(tab()==='Overview'){<div class="overview-grid"><article><h3>Current Conditions</h3><div class="reading-grid">@for(device of space()!.devices.slice(0,4);track device.id){<div><span>{{device.type}}</span><b>{{device.readings.at(-1)?.value}} {{device.readings.at(-1)?.unit}}</b><resq-status-badge [status]="device.status"/></div>}</div><h3>Environmental History</h3><resq-line-chart [multi]="true"/></article><aside><h3>Space information</h3><dl><dt>Room</dt><dd>{{space()!.roomNumber}}</dd><dt>Type</dt><dd>{{space()!.type}}</dd><dt>Sensitivity</dt><dd>{{space()!.sensitivity}}</dd><dt>Devices</dt><dd>{{space()!.devices.length}}</dd><dt>Risk status</dt><dd><resq-status-badge [status]="space()!.status"/></dd></dl></aside></div>}
    @if(tab()==='Devices'){<div class="list-panel">@for(device of space()!.devices;track device.id){<a [routerLink]="'/devices/'+device.id"><span>◉</span><div><b>{{device.name}}</b><small>{{device.code}} · {{device.type}}</small></div><resq-status-badge [status]="device.status"/>→</a>}</div>}
    @if(tab()==='Alerts'){<div class="list-panel">@for(alert of alerts();track alert.id){<a [routerLink]="'/alerts/'+alert.id"><span>△</span><div><b>{{alert.title}}</b><small>{{alert.description}}</small></div><resq-status-badge [status]="alert.status"/>→</a>}</div>}
    @if(tab()==='Monitoring Configuration'){<form class="config" [formGroup]="form" (ngSubmit)="save()"><div class="config-intro"><h3>Monitoring Configuration</h3><p>Adjust sensitivity and risk thresholds. Changes are stored for this demo session.</p></div><label>Sensitivity level<select formControlName="sensitivity"><option>Low</option><option>Normal</option><option>High</option><option>Custom</option></select></label><h4>Environmental thresholds</h4><div class="thresholds">@for(metric of metrics;track metric){<div><span><b>{{metric}}</b><small>{{unit(metric)}}</small></span><label>Warning<input type="number" [formControlName]="metric+'Warning'"/></label><label>Critical<input type="number" [formControlName]="metric+'Critical'"/></label></div>}</div><button type="submit" [disabled]="form.invalid">Save configuration</button></form>}
    @if(tab()==='History'){<article class="history"><h3>Risk History</h3><p><i class="critical"></i><b>Today, 14:32</b><span>Critical</span><small>Gas crossed critical threshold</small></p><p><i class="warning"></i><b>Today, 14:10</b><span>Warning</span><small>Smoke levels increasing</small></p><p><i class="normal"></i><b>Today, 13:48</b><span>Normal</span><small>All conditions within range</small></p><resq-line-chart [multi]="true"/></article>}
  }@else{<div class="not-found"><h2>Space not found</h2><a routerLink="/dashboard">Back to Dashboard</a></div>}
`,styleUrl:'./space-detail.page.scss'})
export class SpaceDetailPage implements OnInit {private readonly fb=inject(FormBuilder);private readonly route=inject(ActivatedRoute);private readonly service=inject(SpaceService);private readonly snack=inject(MatSnackBar);readonly space=signal<Space|undefined>(undefined);readonly tab=signal('Overview');readonly metrics=['Temperature','Smoke','Gas','Humidity'] as const;readonly form=this.fb.nonNullable.group({sensitivity:['Normal' as Space['sensitivity'],Validators.required],TemperatureWarning:[28,Validators.required],TemperatureCritical:[35,Validators.required],SmokeWarning:[80,Validators.required],SmokeCritical:[120,Validators.required],GasWarning:[200,Validators.required],GasCritical:[300,Validators.required],HumidityWarning:[70,Validators.required],HumidityCritical:[85,Validators.required]});ngOnInit():void{const found=SPACES.find(s=>s.id===this.route.snapshot.paramMap.get('spaceId'));this.space.set(found);if(found){const t=found.thresholds;this.form.patchValue({sensitivity:found.sensitivity,TemperatureWarning:t.Temperature?.warning,TemperatureCritical:t.Temperature?.critical,SmokeWarning:t.Smoke?.warning,SmokeCritical:t.Smoke?.critical,GasWarning:t.Gas?.warning,GasCritical:t.Gas?.critical,HumidityWarning:t.Humidity?.warning,HumidityCritical:t.Humidity?.critical})}}alerts(){return ALERTS.filter(a=>a.spaceId===this.space()?.id).slice(0,8)}buildingName(){return BUILDINGS.find(b=>b.id===this.space()?.buildingId)?.name??'—'}floorName(){return FLOORS.find(f=>f.id===this.space()?.floorId)?.name??'—'}unit(metric:string){return metric==='Temperature'?'°C':metric==='Humidity'?'%':'ppm'}save():void{const s=this.space();if(!s||this.form.invalid)return;const v=this.form.getRawValue();const thresholds:SpaceThresholds={Temperature:{warning:v.TemperatureWarning,critical:v.TemperatureCritical},Smoke:{warning:v.SmokeWarning,critical:v.SmokeCritical},Gas:{warning:v.GasWarning,critical:v.GasCritical},Humidity:{warning:v.HumidityWarning,critical:v.HumidityCritical}};this.service.updateConfiguration(s.id,v.sensitivity,thresholds);this.space.set({...s,sensitivity:v.sensitivity,thresholds});this.snack.open('Monitoring configuration updated.','Close',{duration:2500})}}
