import { ChangeDetectionStrategy, Component, OnInit, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { ActivatedRoute, RouterLink } from '@angular/router';
import { Device } from '../../core/models/resq.models';
import { ALERTS, BUILDINGS, DEVICES, FLOORS, SPACES } from '../../core/mock-data/resq.mock';
import { LineChartComponent, StatusBadgeComponent } from '../../shared/ui/ui.components';

@Component({selector:'resq-devices-page',standalone:true,imports:[FormsModule,RouterLink,StatusBadgeComponent],changeDetection:ChangeDetectionStrategy.OnPush,template:`<div class="filters"><label>⌕<input [(ngModel)]="query" (ngModelChange)="apply()" placeholder="Search devices or codes..."/></label><select [(ngModel)]="type" (ngModelChange)="apply()"><option value="">All types</option>@for(item of types;track item){<option>{{item}}</option>}</select><select [(ngModel)]="status" (ngModelChange)="apply()"><option value="">All statuses</option><option>Online</option><option>Warning</option><option>Critical</option><option>Offline</option></select></div><div class="summary"><b>{{filtered().length}} devices</b><span>Across 3 buildings · Last synchronized just now</span></div><div class="table"><table><thead><tr><th>Device</th><th>Code</th><th>Type</th><th>Building</th><th>Floor</th><th>Space</th><th>Status</th><th>Last Reading</th><th>Last Seen</th></tr></thead><tbody>@for(device of filtered();track device.id){<tr [routerLink]="'/devices/'+device.id"><td><span class="device-icon">{{icon(device.type)}}</span><b>{{device.name}}</b></td><td><code>{{device.code}}</code></td><td>{{device.type}}</td><td>{{building(device).name}}</td><td>{{floor(device).name}}</td><td>{{space(device).name}}</td><td><resq-status-badge [status]="device.status"/></td><td><b>{{device.readings.at(-1)?.value}} {{device.readings.at(-1)?.unit}}</b></td><td>{{device.status==='Offline'?'3h ago':'2 min ago'}}</td></tr>}</tbody></table></div>`,styleUrl:'./devices.pages.scss'})
export class DevicesPage {readonly types=['Temperature','Smoke','Gas','Humidity','Motion'];readonly filtered=signal(DEVICES);query='';type='';status='';apply():void{const q=this.query.toLowerCase();this.filtered.set(DEVICES.filter(d=>(!q||`${d.name} ${d.code}`.toLowerCase().includes(q))&&(!this.type||d.type===this.type)&&(!this.status||d.status===this.status)))}space(d:Device){return SPACES.find(s=>s.id===d.spaceId)??SPACES[0]}floor(d:Device){return FLOORS.find(f=>f.id===this.space(d).floorId)??FLOORS[0]}building(d:Device){return BUILDINGS.find(b=>b.id===this.space(d).buildingId)??BUILDINGS[0]}icon(type:string){return type==='Temperature'?'♨':type==='Smoke'?'☁':type==='Gas'?'≋':type==='Humidity'?'◉':'⌁'}}

@Component({selector:'resq-device-detail',standalone:true,imports:[RouterLink,StatusBadgeComponent,LineChartComponent],changeDetection:ChangeDetectionStrategy.OnPush,template:`@if(device()){<div class="detail-head"><div><a routerLink="/devices">← Devices</a><div><span>◉</span><div><h2>{{device()!.name}}</h2><p>{{device()!.code}} · {{device()!.type}} Sensor</p></div></div></div><resq-status-badge [status]="device()!.status"/></div><section class="stats"><article><span>Current Reading</span><b>{{device()!.readings.at(-1)?.value}} {{device()!.readings.at(-1)?.unit}}</b><small>Updated 2 minutes ago</small></article><article><span>Battery Level</span><b>{{device()!.battery}}%</b><small>Estimated 8 months remaining</small></article><article><span>Signal Strength</span><b>{{device()!.signal}} dBm</b><small>Strong connection</small></article><article><span>Last Seen</span><b>{{device()!.status==='Offline'?'3 hours':'2 min'}} ago</b><small>Gateway SC-F2-01</small></article></section><div class="detail-grid"><article class="chart-card"><div class="card-head"><div><h3>Reading History</h3><p>Last 24 hours</p></div><select><option>Last 24 Hours</option><option>Last 7 Days</option></select></div><resq-line-chart/></article><aside><h3>Assigned Location</h3><div class="location"><span>▥</span><div><b>{{buildingName()}}</b><small>{{floorName()}} → {{space()?.name}} · Room {{space()?.roomNumber}}</small></div></div><a [routerLink]="'/spaces/'+space()?.id">View space →</a><h3>Technical Information</h3><dl><dt>Firmware Version</dt><dd>{{device()!.firmware}}</dd><dt>Battery Level</dt><dd>{{device()!.battery}}%</dd><dt>Signal Strength</dt><dd>{{device()!.signal}} dBm</dd><dt>Protocol</dt><dd>LoRaWAN</dd><dt>Sampling Rate</dt><dd>60 seconds</dd></dl></aside><article class="alerts-card"><h3>Recent Alerts</h3>@for(alert of alerts();track alert.id){<a [routerLink]="'/alerts/'+alert.id"><span>!</span><div><b>{{alert.title}}</b><small>{{alert.description}}</small></div><resq-status-badge [status]="alert.status"/></a>}</article></div>}@else{<div class="not-found"><h2>Device not found</h2><a routerLink="/dashboard">Back to Dashboard</a></div>}`,styleUrl:'./device-detail.page.scss'})
export class DeviceDetailPage implements OnInit {readonly device=signal<Device|undefined>(undefined);constructor(private readonly route:ActivatedRoute){}ngOnInit():void{this.device.set(DEVICES.find(d=>d.id===this.route.snapshot.paramMap.get('deviceId')))}space(){return SPACES.find(s=>s.id===this.device()?.spaceId)}floorName(){return FLOORS.find(f=>f.id===this.space()?.floorId)?.name??'—'}buildingName(){return BUILDINGS.find(b=>b.id===this.space()?.buildingId)?.name??'—'}alerts(){return ALERTS.filter(a=>a.deviceId===this.device()?.id||a.spaceId===this.space()?.id).slice(0,4)}}
